### ISSUE TITLE
Infografìa unidad 1

### ISSUE THREAD

**Issue by Kevinaleatorio** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Kevinaleatorio#3]
[Infografía de gestiòn de proyectos.pdf](https://github.com/user-attachments/files/16753270/Infografia.de.gestion.de.proyectos.pdf)

**Comment by Nelsy21** [comment]
20/20 buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
